# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: test all make targets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for an Erlang is installation
        run: |
          set -xv
          erl +B -noinput -eval 'io:put_chars(erlang:system_info(system_version)),halt(0).'

      - name: Install neptune
        run: |
          PACKAGE_VERSION=0.7.0
          wget https://github.com/grahamcrowe77/autotools-neptune/releases/download/$PACKAGE_VERSION/neptune-$PACKAGE_VERSION.tar.gz
          tar xf neptune-$PACKAGE_VERSION.tar.gz
          pushd neptune-$PACKAGE_VERSION
          ./configure --prefix=/usr
          make V=1
          sudo make install V=1
          popd

      - name: Bootstrap
        run: |
          set -xv
          ./bootstrap.sh
          
      - name: Configure
        run:
          ./configure --prefix=/usr

      - name: Build
        run:
          make V=1

      - name: Test
        run:
          make check V=1 TESTSUITEFLAGS=-v

      - name: Install (DESTDIR)
        run: |
          make install DESTDIR=$PWD/inst V=1 TESTSUITEFLAGS=-v
          make installcheck DESTDIR=$PWD/inst V=1 TESTSUITEFLAGS=-v
